import { defineConfig } from 'tsdown'

/** Build the Host loader entries from the tsc-emitted sources. The Typert
 * Remote protocol files (typert.host + typert.remote-client) are generated by
 * the `gen:typert` step through the scratch workspace in
 * `../.typert-build` (the generator requires the harness monorepo layout). */
export default defineConfig({
  entry: ['lib/types/index.js', 'lib/types/invariant.js'],
  outDir: 'lib',
  format: ['esm'],
  platform: 'node',
  target: 'es2024',
  fixedExtension: false,
  dts: false,
  clean: false,
})
