/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { AccountBalanceQuotaSnapshot, AccountBalanceStatusSnapshot } from '@lovstudio/dsh-account-balance/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6163636f756e7442616c616e6365 {
    quotas: () => Promise<RemoteResult<AccountBalanceQuotaSnapshot>>
    status: () => Promise<RemoteResult<AccountBalanceStatusSnapshot>>
  }
  interface TypertRemoteMap {
    'accountBalance/quotas': () => Promise<RemoteResult<AccountBalanceQuotaSnapshot>>
    'accountBalance/status': () => Promise<RemoteResult<AccountBalanceStatusSnapshot>>
  }
  interface TypertRemoteNamespaceMap {
    'accountBalance': TypertRemoteNamespace$6163636f756e7442616c616e6365
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
