/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _lovstudio_dsh_account_balance_accountBalance_quotas_result$schema = z.object({
  'at': z.number().readonly(),
  'rows': z.object({
  'glm': z.object({
  'mode': z.literal("windows").readonly(),
  'status': z.union([z.literal("ok"), z.literal("no-key"), z.literal("no-data"), z.literal("error")]).readonly(),
  'windows': z.object({
  'w5': z.object({
  'pct': z.number().readonly(),
  'used': z.number().readonly(),
  'remaining': z.number().readonly(),
  'resetAt': z.number().readonly(),
}).readonly(),
  'week': z.object({
  'pct': z.number().readonly(),
  'used': z.number().readonly(),
  'remaining': z.number().readonly(),
  'resetAt': z.number().readonly(),
}).readonly(),
}).readonly(),
}).readonly(),
  'kimi': z.object({
  'mode': z.literal("windows").readonly(),
  'status': z.union([z.literal("ok"), z.literal("no-key"), z.literal("no-data"), z.literal("error")]).readonly(),
  'windows': z.object({
  'w5': z.object({
  'pct': z.number().readonly(),
  'used': z.number().readonly(),
  'remaining': z.number().readonly(),
  'resetAt': z.number().readonly(),
}).readonly(),
  'week': z.object({
  'pct': z.number().readonly(),
  'used': z.number().readonly(),
  'remaining': z.number().readonly(),
  'resetAt': z.number().readonly(),
}).readonly(),
}).readonly(),
}).readonly(),
  'or': z.object({
  'mode': z.literal("balance").readonly(),
  'status': z.union([z.literal("ok"), z.literal("no-key"), z.literal("no-data"), z.literal("error")]).readonly(),
  'balance': z.number().readonly(),
  'detail': z.string().readonly(),
}).readonly(),
  'ds': z.object({
  'mode': z.literal("balance").readonly(),
  'status': z.union([z.literal("ok"), z.literal("no-key"), z.literal("no-data"), z.literal("error")]).readonly(),
  'balance': z.number().readonly(),
  'detail': z.string().readonly(),
}).readonly(),
}).readonly(),
})
const _lovstudio_dsh_account_balance_accountBalance_status_result$schema = z.object({
  'sessions': z.number().readonly(),
  'tasks': z.number().readonly(),
})

export const TYPERT = {
  package: '@lovstudio/dsh-account-balance',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@lovstudio/dsh-account-balance#accountBalance/quotas',
      service: 'accountBalance',
      namespace: 'accountBalance',
      method: 'quotas',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@lovstudio/dsh-account-balance/types#AccountBalanceQuotaSnapshot',
        schema: _lovstudio_dsh_account_balance_accountBalance_quotas_result$schema,
      },
      sourceLocation: {"file":"packages/account-balance/src/index.ts","line":137,"column":9},
    },
    {
      id: '@lovstudio/dsh-account-balance#accountBalance/status',
      service: 'accountBalance',
      namespace: 'accountBalance',
      method: 'status',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@lovstudio/dsh-account-balance/types#AccountBalanceStatusSnapshot',
        schema: _lovstudio_dsh_account_balance_accountBalance_status_result$schema,
      },
      sourceLocation: {"file":"packages/account-balance/src/index.ts","line":113,"column":3},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
