/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { TaskPulseQuotaSnapshot, TaskPulseStatusSnapshot } from '@lovstudio/dsh-task-pulse/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$7461736b50756c7365 {
    quotas: () => Promise<RemoteResult<TaskPulseQuotaSnapshot>>
    status: () => Promise<RemoteResult<TaskPulseStatusSnapshot>>
  }
  interface TypertRemoteMap {
    'taskPulse/quotas': () => Promise<RemoteResult<TaskPulseQuotaSnapshot>>
    'taskPulse/status': () => Promise<RemoteResult<TaskPulseStatusSnapshot>>
  }
  interface TypertRemoteNamespaceMap {
    'taskPulse': TypertRemoteNamespace$7461736b50756c7365
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
